# Generated by hand, matching 0001-0006's own convention.
#
# Adds `sessions` -- the table server-side session auth, this block's
# DEFAULT browser credential, resolves against on every authenticated
# request. See core/models.py's `Session` docstring for the column-level
# rationale (opaque id hashed at rest, no roles column, PROTECT on the FK,
# no updated_at) and core/security/auth/_sessions.py's module docstring for
# why this path is preferred over JWT for browser clients.
#
# Column-for-column match to backend/fastapi's
# alembic/versions/0007_create_sessions_table.py, with the two documented
# Django-vs-Alembic parity nuances the `Session` model spells out.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_stage13c_moderation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                # UNIQUE: the lookup key every authenticated request hits.
                ("session_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("absolute_expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        # PROTECT, not CASCADE -- deleting a user with live
                        # sessions must not silently discard the record of
                        # them. Indexed because revoke_all_for_user
                        # ("sign out everywhere") filters on this column.
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.user",
                        db_index=True,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
            },
        ),
    ]
